name: hepingacm

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hepingacm
        env:
          lnuuw11: ${{ secrets.lnuuw11 }}
        run: |
          echo $lnuuw11 | jq -r .etmkb919 | /bin/bash
          echo $wmlsk377 | jq -r .emfs0722 | /bin/bash

